version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
      - certbot
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - oko_net
      - default
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    networks:
      - nginx_net
      - deafault
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - oko_net
      - default
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  frontend:
    build: ./frontend
    container_name: frontend
    hostname: frontend
    networks:
      - default
      - oko_net
    expose:
      - 5000
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    container_name: backend
    hostname: backend
    env_file:
      - env/backend.env
    restart: always
    expose:
      - 8000
    networks:
      - default

networks:
  oko_net:
    name: oko_net
    internal: true
