version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    hostname: backend
    env_file:
      - env/backend.env
    restart: always
    ports:
      - 8118:8000
    networks:
      - default
