name: CI

on: [push, pull_request]

jobs:        
  deploy-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/backend'
    steps:
      - uses: actions/checkout@v2

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/dekanat_keys 
            git fetch --all
            git reset --hard origin/backend
            docker-compose up --build -d docker-compose up -d --build --force-recreate
